defmodule PhoenixAsh.Repo.Migrations.AddUserAndToken do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
    end

    create table(:token, primary_key: false) do
    end

    alter table(:user) do
      add :email, :citext, null: false
    end

    alter table(:token) do
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    alter table(:user) do
      add :hashed_password, :text, null: false
    end

    create unique_index(:user, [:email], name: "user_unique_email_index")

    alter table(:token) do
      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end
  end

  def down do
    alter table(:token) do
      remove :jti
      remove :subject
      remove :expires_at
      remove :purpose
      remove :extra_data
    end

    drop_if_exists unique_index(:user, [:email], name: "user_unique_email_index")

    alter table(:user) do
      remove :hashed_password
    end

    alter table(:token) do
      remove :created_at
      remove :updated_at
    end

    alter table(:user) do
      remove :email
    end

    drop table(:token)

    drop table(:user)
  end
end